dist: xenial
sudo: yes

language: python

python: 3.7

install:
  - pip install codecov
  - pip install -r requirements.txt
  - pip install .

script:
  - coverage run test.py
  - python setup.py test

after_success:
  - codecov
